Python Assignment

Project Overview
This assignment aims to provide a comprehensive understanding of Python programming fundamentals. You will create code examples to demonstrate your proficiency in various Python concepts.

Task
Create a Jupyter Notebook to document your code and explanations.
Write at least five code examples for each of the following concepts:
Python Functions
Lambda Functions
NumPy
Pandas
If Statements
Loops (for and while)
Lists, Tuples, Sets, Dictionaries
Operators (arithmetic, comparison, logical, etc.)
Reading CSV files
Python String Methods



Concepts to Cover

Python Functions

Create functions with different numbers of parameters and return types.
Explore function scope and variable accessibility.
Implement functions with default argument values.
Write recursive functions.
Demonstrate how to use docstrings to document functions.


Lambda Functions

Create simple lambda functions for various operations.
Use lambda functions with built-in functions like map, filter, and reduce.
Compare lambda functions with regular functions in terms of syntax and use cases.

NumPy

Create different types of NumPy arrays (1D, 2D, 3D).

Perform basic arithmetic operations on arrays.
Use indexing and slicing to access elements.
Explore array manipulation functions (reshape, transpose, concatenate).
Create and use NumPy random number generators.

Pandas

Create Pandas Series and DataFrames.
Load data from various file formats (CSV, Excel, etc.).
Perform data cleaning and manipulation tasks.
Explore data analysis and visualization using Pandas.
Create pivot tables and group data for analysis.

If Statements

Demonstrate conditional logic using if, else, and elif statements.
Create complex conditional expressions.
Implement nested if statements.

Loops

Use for loops to iterate over sequences.
Employ while loops for indefinite iteration.
Implement nested loops.
Utilize break and continue statements.

Lists, Tuples, Sets, Dictionaries

Create and manipulate lists, tuples, sets, and dictionaries.
Understand the differences between these data structures.
Perform operations like indexing, slicing, adding, removing elements.
Explore built-in methods for each data structure.

Operators

Use arithmetic, comparison, logical, and assignment operators.
Understand operator precedence.
Apply operators in expressions and calculations.
Reading CSV files
Read CSV files into Pandas DataFrames.
Explore different CSV reading options and parameters.
Handle missing values and data cleaning.

Python String Methods

Manipulate strings using various built-in methods.
Perform operations like concatenation, slicing, finding substrings.
Convert strings to uppercase, lowercase, and title case.
Remove whitespace and split strings.


Submission
Save your Jupyter Notebook as a PDF.
Submit the PDF by Monday.
Additional Tips
Use clear and concise code comments to explain your code.
Experiment with different approaches and libraries to enhance your learning.
Refer to online resources and documentation for further exploration.


## Python Functions


In [ ]:
## Create functions with different numbers of parameters and return types.

def calculate_area(length, width):
  area = length * width
  return area

area = calculate_area(5,2.3)
print(f"Area : {area}")
print(f"Type : {type(area)}")




Area : 11.5
Type : <class 'float'>


In [ ]:
## Function Scopes and variable accesibilty

def outer_function():  # step 1 : defined outer function : not executed yet
  outer_variable = "Outer variable" # step 3: executed initialized variable

  def inner_function(): #step 4 : defined inner function : not executed yet
    inner_var = "Inner variable" # step 6 : executed initialized variable
    print(outer_variable)  # step 7 : executed print statement
    return inner_var # step 8 : store inner var

  results = inner_function() # step 5 : call inner function
  print(results) # step 9 : print stored inner var here

outer_function() # step 2 : call outer function
print("completed") # step 10 : last execution


Outer variable
Inner variable
completed


In [ ]:
## Implement functions with default argument values.

def generate_greeting(name, greeting = "Hello", punctuation = "!"):
  return f"{greeting}, {name} {punctuation}"

print(generate_greeting("Sandip"))
print(generate_greeting("Jyonita","Hi","."))



Hello, Sandip !
Hi, Jyonita .


In [ ]:
# recursive

def factorial(n):



In [ ]:
## Recursive Functions

def nfactorial(m):
  if m == 1:
    return 1
  return m * nfactorial(m-1)

print(nfactorial(5))

120


In [ ]:
## Demonstrate how to use docstrings to document functions.

import re

def analyze_text(text):

  """
  Analyze a given text to count the numnber of words and sentences.

  parameters:
  text( str): The text to be analyzed.

  Returns:
  dict: A dictionary with word and sentence counts.

  """
  sentences = re.split(r'[.!?]',text)
  word_count = sum(len(sentence.split()) for sentence in sentences if sentence.strip())
  sentence_count = len([s for s in sentences if s.strip()])

  return {"Words": word_count, "Sentences": sentence_count}

# Example Usage:
text = "Hello world! This is a test. How many words and sentences are here?"
print(analyze_text(text))



{'Words': 13, 'Sentences': 3}


### Lambda Functions



In [ ]:
# Create simple lambda functions for various operations.
a = lambda x:x*5
print(a(5))

b = lambda y,z:y+z
print(b(1,2))

c = lambda p,q:p if p>q else q
print(c(9,7))

25
3
9


In [ ]:
# Use lambda functions with built-in functions like map, filter, and reduce.

from functools import reduce

# Map
lst = [1,2,3,4,5]
x = list(map(lambda x: x**2,lst))
print(f"Map example : {x}")

# Filter
lst2 = [1,2,3,4,5]
y = list(filter(lambda y:y%2==0,lst2))
print(f"Filter example : {y}")

# Reduce
lst3 = [1,2,3,4,5]
z = reduce(lambda x,y:x+y,lst3)
print(f"Reduce example : {z}")

# combinig map,filter, and reduce
lst4 = [1,2,3,4,5,6]
a = list(filter(lambda x:x%2==0,lst4))
b = list(map(lambda x:x**2,a))
c = reduce(lambda x,y : x+y,b)
print(c)

Map example : [1, 4, 9, 16, 25]
Filter example : [2, 4]
Reduce example : 15
56


In [ ]:
# Compare lambda functions with regular functions in terms of syntax and use cases.

add = lambda x,y : x+y
print(add(2,3))

#normal function
def add(a,b):
  return a+b
print(add(2,3))


5
5


## Numpy

In [24]:
# Create different types of NumPy arrays (1D, 2D, 3D).

import numpy as np

# 1D Array
array1 = np.array([1,2,3,4])
print(f"1D array: {array1}")
print("\n")

# 2D Array
array2 = np.array([[1,2,3],[4,5,6]])
print(f"2D Array: {array2}")
print("\n")

# 3D array
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"3D Array: {array3}")

# 2D array using reshape
array_reshaped = np.arange(1, 13).reshape(3, 4)  # 3 rows, 4 columns
print("\n2D Array with reshape:")
print(array_reshaped)

1D array: [1 2 3 4]


2D Array: [[1 2 3]
 [4 5 6]]


3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

2D Array with reshape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
# Perform basic arithmetic operations on arrays.
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
result_add = array1 + array2
print("Addition:")
print(result_add)

# Element-wise multiplication
result_mul = array1 * array2
print("\nMultiplication:")
print(result_mul)


# Element-wise division
result_div = array2 / array1
print("\nDivision:")
print(result_div)

Addition:
[5 7 9]

Multiplication:
[ 4 10 18]

Division:
[4.  2.5 2. ]


In [30]:
# Use indexing and slicing to access elements.

# 1D Array
array_1d = np.array([10, 20, 30, 40, 50])

# Access the first element
print("First element:", array_1d[0])

# Access the last element
print("Last element:", array_1d[-1])

# Slice elements from index 1 to 3 (exclusive)
print("\nSliced elements (1 to 3):", array_1d[1:4])

# Slice with a step
print("Every second element:", array_1d[::2])

# Slice in reverse order
print("Reversed array:", array_1d[::-1])

First element: 10
Last element: 50

Sliced elements (1 to 3): [20 30 40]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [33]:
#Explore array manipulation functions (reshape, transpose, concatenate).

import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2D (2 rows, 3 columns)
array_2d = array.reshape(2, 3)
print("Reshaped to 2D (2x3):\n", array_2d)

# Reshape to 3D (2 layers, 1 row, 3 columns)
array_3d = array.reshape(2, 1, 3)
print("\nReshaped to 3D (2x1x3):\n", array_3d)

# Create a 2D array
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Transpose rows to columns
transposed = matrix.transpose()
print("\nOriginal Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed)

# Alternative using `.T` attribute
print("Using .T attribute:\n", matrix.T)

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate along axis 0 (default)
concatenated_1d = np.concatenate((array1, array2))
print("\nConcatenated 1D Array:\n", concatenated_1d)

# Create two 2D arrays
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_2d_rows = np.concatenate((array_2d_1, array_2d_2), axis=0)
print("\nConcatenated 2D Array (Rows):\n", concatenated_2d_rows)

# Concatenate along axis 1 (columns)
concatenated_2d_cols = np.concatenate((array_2d_1, array_2d_2), axis=1)
print("Concatenated 2D Array (Columns):\n", concatenated_2d_cols)



Reshaped to 2D (2x3):
 [[1 2 3]
 [4 5 6]]

Reshaped to 3D (2x1x3):
 [[[1 2 3]]

 [[4 5 6]]]

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Matrix:
 [[1 3 5]
 [2 4 6]]
Using .T attribute:
 [[1 3 5]
 [2 4 6]]

Concatenated 1D Array:
 [1 2 3 4 5 6]

Concatenated 2D Array (Rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated 2D Array (Columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [35]:
# Create and use NumPy random number generators.
import numpy as np

# Uniform distribution [0, 1)
random_floats = np.random.rand(5)  # Generate 5 random floats
print("Random Floats (Uniform [0, 1)):", random_floats)

# Normal distribution (mean=0, std=1)
random_normals = np.random.randn(5)  # Generate 5 random values from normal distribution
print("Random Floats (Normal Distribution):", random_normals)

# Random floats using random_sample
random_samples = np.random.random_sample((2, 3))  # 2x3 array of random floats
print("Random Floats (Array 2x3):\n", random_samples)


# Random integers between 1 (inclusive) and 10 (exclusive)
random_integers = np.random.randint(1, 10, size=5)
print("\nRandom Integers [1, 10):", random_integers)

# 2D array of random integers
random_int_array = np.random.randint(1, 100, size=(3, 4))
print("2D Array of Random Integers:\n", random_int_array)


Random Floats (Uniform [0, 1)): [0.59710516 0.99301542 0.94155374 0.87385128 0.9812067 ]
Random Floats (Normal Distribution): [-0.1111842  -0.84919373 -0.17682347  0.71006823  0.34409061]
Random Floats (Array 2x3):
 [[0.29328224 0.9796407  0.67912758]
 [0.08991639 0.93031041 0.0956051 ]]

Random Integers [1, 10): [5 7 1 3 7]
2D Array of Random Integers:
 [[96 12 33 88]
 [71 27 43 93]
 [24 83 71 60]]


## Pandas

In [39]:
# Create Pandas Series and DataFrames.
import pandas as pd

# Creating a Series from a list
data_list = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data_list)
print("Series from List:\n", series_from_list)

# Creating a DataFrame from a dictionary
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
df_from_dict = pd.DataFrame(data_dict)
print("\nDataFrame from Dictionary:\n", df_from_dict)

# Creating a DataFrame from a list of lists
data_list = [
    ['Alice', 25, 50000],
    ['Bob', 30, 60000],
    ['Charlie', 35, 70000]
]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age', 'Salary'])
print("\nDataFrame from List of Lists:\n", df_from_list)

import numpy as np

# Creating a DataFrame from a numpy array
array_data = np.random.rand(3, 3)
df_from_array = pd.DataFrame(array_data, columns=['Col1', 'Col2', 'Col3'])
print("\nDataFrame from Numpy Array:\n", df_from_array)



Series from List:
 0    10
1    20
2    30
3    40
4    50
dtype: int64

DataFrame from Dictionary:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

DataFrame from List of Lists:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

DataFrame from Numpy Array:
        Col1      Col2      Col3
0  0.712304  0.144397  0.254091
1  0.283265  0.313518  0.220760
2  0.364333  0.376149  0.707681


In [2]:
# Load data from various file formats (CSV, Excel, etc.).
import pandas as pd

# Load CSV file
csv_df = pd.read_csv('news_raw_data.csv')
print("DataFrame from CSV:\n", csv_df)


DataFrame from CSV:
                                               source  \
0                   {'id': 'wired', 'name': 'Wired'}   
1                   {'id': 'wired', 'name': 'Wired'}   
2                   {'id': 'wired', 'name': 'Wired'}   
3        {'id': None, 'name': 'Yahoo Entertainment'}   
4           {'id': 'the-verge', 'name': 'The Verge'}   
..                                               ...   
75             {'id': None, 'name': 'Science Daily'}   
76             {'id': None, 'name': 'Johnhawks.net'}   
77                  {'id': None, 'name': 'BBC News'}   
78  {'id': 'new-scientist', 'name': 'New Scientist'}   
79               {'id': None, 'name': 'Wikihow.com'}   

                      author  \
0                Steven Levy   
1                Will Knight   
2              David Gilbert   
3              Lawrence Bonk   
4                  Emma Roth   
..                       ...   
75                       NaN   
76                John Hawks   
77                

In [4]:
!pip install openpyxl

    tinycss2 (>=1.1.0<1.2) ; extra == 'css'
             ~~~~~~~~^

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [5]:
# Load Excel file
excel_df = pd.read_excel('Book1.xlsx')
print("\nDataFrame from Excel:\n", excel_df)


DataFrame from Excel:
 Empty DataFrame
Columns: []
Index: []


In [7]:
# Load JSON file
json_df = pd.read_json('raw_json.json')
print("\nDataFrame from JSON:\n", json_df)


DataFrame from JSON:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


## If Statements

In [8]:
# Demonstrate conditional logic using if, else, and elif statements.

# Grade classification with additional condition
score = 85

if score >= 90:
    print("Grade: A")
else:
    if score >= 80:
        print("Grade: B")
    else:
        print("Grade: C")
        
        


Grade: B


In [9]:
# Determine if a year is a leap year
year = 2024

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


2024 is a leap year.


In [10]:
# Ask for user input and provide feedback
user_input = input("Enter a number: ")
number = int(user_input)

if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


Enter a number: 5
The number is positive.


In [11]:
# Check the type of triangle based on side lengths
a, b, c = 5, 5, 8

if a == b == c:
    print("The triangle is equilateral.")
elif a == b or b == c or a == c:
    print("The triangle is isosceles.")
else:
    print("The triangle is scalene.")


The triangle is isosceles.


In [12]:
# Create complex conditional expressions.

# Determine a student’s scholarship eligibility
gpa = 3.8
extracurriculars = True
volunteer_hours = 50

if gpa >= 3.5:
    if extracurriculars or volunteer_hours >= 40:
        print("Eligible for a scholarship.")
    else:
        print("Not eligible for a scholarship due to insufficient activities.")
else:
    print("Not eligible for a scholarship due to low GPA.")


Eligible for a scholarship.


In [13]:
# Evaluate job application criteria

application = {
    "education": "Bachelor's",
    "experience_years": 5,
    "skills": ["Python", "Machine Learning", "SQL"]
}

if application["education"] in ["Bachelor's", "Master's"] and application["experience_years"] >= 3:
    if "Python" in application["skills"] and "SQL" in application["skills"]:
        print("Application approved.")
    else:
        print("Missing required skills.")
else:
    print("Does not meet education or experience requirements.")


Application approved.


In [14]:
# Categorize a number into different ranges
number = 45

if 0 <= number <= 20:
    print("The number is in the range 0-20.")
elif 21 <= number <= 40:
    print("The number is in the range 21-40.")
elif 41 <= number <= 60:
    print("The number is in the range 41-60.")
else:
    print("The number is out of range.")


The number is in the range 41-60.


In [15]:
# Implement nested if statements.
age = 25
citizenship = "Canada"
criminal_record = False

if age >= 18:
    if citizenship == "Canada":
        if not criminal_record:
            print("You are eligible to vote.")
        else:
            print("You are not eligible due to a criminal record.")
    else:
        print("You must be a citizen of Canada to vote.")
else:
    print("You are not old enough to vote.")


You are eligible to vote.


In [16]:
score = 85

if score >= 50:
    print("You passed.")
    if score >= 90:
        print("Grade: A")
    elif score >= 80:
        print("Grade: B")
    elif score >= 70:
        print("Grade: C")
    else:
        print("Grade: D")
else:
    print("You failed.")


You passed.
Grade: B


## Loops

In [23]:
# Use for loops to iterate over sequences

fruits = ["apple", "banana", "cherry", "date"]

for i in fruits:
    print(i)
print("\n")    
colors = ("red", "green", "blue", "yellow")

# Using for loop to iterate over a tuple
for color in colors:
    print(color)
print("\n")

student_scores = {
    "Alice": 85,
    "Bob": 90,
    "Charlie": 78
}

# Iterate over dictionary keys
for student in student_scores:
    print(student)

# Iterate over dictionary values
for score in student_scores.values():
    print(score)

# Iterate over both keys and values
for student, score in student_scores.items():
    print(f"{student} scored {score}")

    

apple
banana
cherry
date


red
green
blue
yellow


Alice
Bob
Charlie
85
90
78
Alice scored 85
Bob scored 90
Charlie scored 78


In [26]:
# Employ while loops for indefinite iteration.

i = 1
while i < 5:
    print(i)
    i +=1

1
2
3
4


In [27]:
while True:
    user_input = input("Enter 'exit' to stop the loop: ")
    if user_input.lower() == 'exit':
        break


Enter 'exit' to stop the loop: exit


In [29]:
valid_input = False

while not valid_input:
    user_age = int(input("Enter your age: "))
    if user_age >= 18:
        print("You are eligible.")
        valid_input = True
    else:
        print("You are not eligible. Try again.")


Enter your age: 17
You are not eligible. Try again.
Enter your age: 19
You are eligible.


In [31]:
# Implement nested loops.

# Multiplication table using nested loops
for i in range(1, 6):  # Outer loop for rows (1-5)
    for j in range(1, 6):  # Inner loop for columns (1-5)
        print(f"{i} x {j} = {i * j}", end="\t")
    print()  # Move to the next line after each row


1 x 1 = 1	1 x 2 = 2	1 x 3 = 3	1 x 4 = 4	1 x 5 = 5	
2 x 1 = 2	2 x 2 = 4	2 x 3 = 6	2 x 4 = 8	2 x 5 = 10	
3 x 1 = 3	3 x 2 = 6	3 x 3 = 9	3 x 4 = 12	3 x 5 = 15	
4 x 1 = 4	4 x 2 = 8	4 x 3 = 12	4 x 4 = 16	4 x 5 = 20	
5 x 1 = 5	5 x 2 = 10	5 x 3 = 15	5 x 4 = 20	5 x 5 = 25	


In [35]:
# Printing a triangle pattern using nested while loops
rows = 5  # Number of rows
i = 1
while i <= rows:  # Outer loop for rows
    j = 1
    while j <= i:  # Inner loop for columns
        print("*", end=" ")
        j += 1
    print("\n")    
    #print()  # Move to the next line after each row
    i += 1


* 

* * 

* * * 

* * * * 

* * * * * 



In [36]:
# Utilize break and continue statements.

# Example: Use break to stop the loop when a specific number is found
numbers = [5, 8, 12, 15, 20, 25, 30]
target = 20

for i in numbers:
    if i == target:
        print("target found")
        break
    print(f"Checking Target {i}.. ")    
        

Checking Target 5.. 
Checking Target 8.. 
Checking Target 12.. 
Checking Target 15.. 
target found


In [37]:
# Example: Use continue to skip even numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

for i in numbers:
    if i%2==0:
        continue
    print(f"odd number {i}..")    

odd number 1..
odd number 3..
odd number 5..
odd number 7..
odd number 9..


## Lists, Tuples, Sets, Dictionaries

In [39]:
# Create and manipulate lists, tuples, sets, and dictionaries.

# List

# Creating a list with different data types
my_list = [1, 2, 3, 4, 5, "Hello", 3.14]
print(my_list)

my_list.append("World")  # Adds "World" to the end of the list
print(my_list)

my_list.insert(2, "Inserted")  # Inserts "Inserted" at index 2
print(my_list)



[1, 2, 3, 4, 5, 'Hello', 3.14]
[1, 2, 3, 4, 5, 'Hello', 3.14, 'World']
[1, 2, 'Inserted', 3, 4, 5, 'Hello', 3.14, 'World']


In [40]:
# Tuple (Immutable)
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple)

print(my_tuple[1])  # Access element at index 1


(1, 2, 3, 4, 5)
2


In [42]:
# Set (Unique)

my_set = {1, 2, 3, 4, 5,5}
print(my_set)

my_set.add(6)  # Adds 6 to the set
print(my_set)

my_set.update([7, 8, 9])  # Adds multiple elements
print(my_set)


{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [46]:
# Dictonaries
my_dict = {"name": "Alice", "age": 25, "city": "New York"}
print(my_dict)

keys = my_dict.keys()  # Get all keys
print(keys)

values = my_dict.values()  # Get all values
print(values)

items = my_dict.items()  # Get all key-value pairs
print(items)

del my_dict["city"]  # Removes the key "city" and its value
print(my_dict)

popped_value = my_dict.pop("name")  # Removes "name" and returns its value
print(f"Popped value: {popped_value}")
print(my_dict)


age = my_dict.get("age", "Not Found")  # Retrieve value with a fallback default
print(age)


nested_dict = {
    "person1": {"name": "Alice", "age": 25},
    "person2": {"name": "Bob", "age": 30}
}

print(nested_dict["person1"]["name"])  # Access "Alice" inside nested dict



{'name': 'Alice', 'age': 25, 'city': 'New York'}
dict_keys(['name', 'age', 'city'])
dict_values(['Alice', 25, 'New York'])
dict_items([('name', 'Alice'), ('age', 25), ('city', 'New York')])
{'name': 'Alice', 'age': 25}
Popped value: Alice
{'age': 25}
25
Alice


## Operators

In [47]:
# Use arithmetic, comparison, logical, and assignment operators.

a = 10
b = 5

# Addition
print(f"a + b = {a + b}")  # 15

# Subtraction
print(f"a - b = {a - b}")  # 5

# Multiplication
print(f"a * b = {a * b}")  # 50

# Division
print(f"a / b = {a / b}")  # 2.0

# Floor Division
print(f"a // b = {a // b}")  # 2

# Modulo
print(f"a % b = {a % b}")  # 0

# Exponentiation
print(f"a ** b = {a ** b}")  # 100000


a + b = 15
a - b = 5
a * b = 50
a / b = 2.0
a // b = 2
a % b = 0
a ** b = 100000


In [48]:
x = 10
y = 5

# Equal to
print(f"x == y: {x == y}")  # False

# Not equal to
print(f"x != y: {x != y}")  # True

# Greater than
print(f"x > y: {x > y}")  # True

# Less than
print(f"x < y: {x < y}")  # False

# Greater than or equal to
print(f"x >= y: {x >= y}")  # True

# Less than or equal to
print(f"x <= y: {x <= y}")  # False


x == y: False
x != y: True
x > y: True
x < y: False
x >= y: True
x <= y: False


In [49]:
a = True
b = False

# and operator
print(f"a and b: {a and b}")  # False

# or operator
print(f"a or b: {a or b}")  # True

# not operator
print(f"not a: {not a}")  # False
print(f"not b: {not b}")  # True


a and b: False
a or b: True
not a: False
not b: True


In [50]:
x = 10

# Assign value
x = 5
print(f"x = {x}")  # 5

# Add and assign
x += 3  # Equivalent to x = x + 3
print(f"x += 3: {x}")  # 8

# Subtract and assign
x -= 2  # Equivalent to x = x - 2
print(f"x -= 2: {x}")  # 6

# Multiply and assign
x *= 4  # Equivalent to x = x * 4
print(f"x *= 4: {x}")  # 24

# Divide and assign
x /= 6  # Equivalent to x = x / 6
print(f"x /= 6: {x}")  # 4.0

# Floor divide and assign
x //= 2  # Equivalent to x = x // 2
print(f"x //= 2: {x}")  # 2

# Modulo and assign
x %= 2  # Equivalent to x = x % 2
print(f"x %= 2: {x}")  # 0

# Exponentiate and assign
x = 5
x **= 3  # Equivalent to x = x ** 3
print(f"x **= 3: {x}")  # 125


x = 5
x += 3: 8
x -= 2: 6
x *= 4: 24
x /= 6: 4.0
x //= 2: 2.0
x %= 2: 0.0
x **= 3: 125


In [51]:
# Understand operator precedence.
x = (5 + 2) * (3 ** 2) / (4 - 1)
print(x)


21.0


Parentheses () are evaluated first:

5 + 2 = 7
3 ** 2 = 9
4 - 1 = 3
Expression becomes: 7 * 9 / 3
Then, multiplication and division are evaluated from left to right:

7 * 9 = 63
63 / 3 = 21

In [ ]:
Python String Methods
Manipulate strings using various built-in methods.
Perform operations like concatenation, slicing, finding substrings.
Convert strings to uppercase, lowercase, and title case.
Remove whitespace and split strings.


## Python String Methods

In [53]:
# Manipulate strings using various built-in methods.

string1 = "Hello"
string2 = 'World'
string3 = '''This is a multi-line
string'''

text = "Python"
print(len(text))  # Output: 6

# Convert strings to uppercase, lowercase, and title case.
text = "hello python"
print(text.upper())    # Output: "HELLO PYTHON"
print(text.lower())    # Output: "hello python"
print(text.capitalize())  # Output: "Hello python"
print(text.title())       # Output: "Hello Python"

# Remove whitespace and split strings.
text = "   Python programming   "
print(text.strip())   # Output: "Python programming"
print(text.lstrip())  # Output: "Python programming   "
print(text.rstrip())  # Output: "   Python programming"

text = "Python is fun, Python is cool"
print(text.find("Python"))  # Output: 0
print(text.rfind("Python")) # Output: 14  index of last occurence
print(text.count("Python")) # Output: 2


6
HELLO PYTHON
hello python
Hello python
Hello Python
Python programming
Python programming   
   Python programming
0
15
2


In [55]:
# Perform operations like concatenation, slicing, finding substrings.
str1 = "Hello"
str2 = "World"
str3 = "How"
str4 = "are"
str5 = "you?"
result = str1 + " " + str2 + ", " + str3 + " " + str4 + " " + str5
print(result)  # Output: "Hello World, How are you?"

text = "Python Programming"

# Slice from index 0 to 5 (exclusive)
substring = text[0:5]
print(substring)  # Output: "Python"

# Slice from index 7 to the end of the string
substring2 = text[7:]
print(substring2)  # Output: "Programming"

# Slice from the beginning to index 6 (exclusive)
substring3 = text[:6]
print(substring3)  # Output: "Python"

# Negative index: Start from the second last character
substring4 = text[-2:]
print(substring4)  # Output: "ng"

# Slicing with a step: Get every second character
substring5 = text[0:12:2]
print(substring5)  # Output: "Pto rg"


text = "Python is amazing"

# Using find() to find the index of the substring "is"
index_of_is = text.find("is")
print(index_of_is)  # Output: 7 (position of "is")

# If substring is not found, find() returns -1
index_of_not_found = text.find("Java")
print(index_of_not_found)  # Output: -1

# Using index() to find the index of the substring "amazing"
index_of_amazing = text.index("amazing")
print(index_of_amazing)  # Output: 11



Hello World, How are you?
Pytho
Programming
Python
ng
Pto rg
7
-1
10
